source 'https://ruby.taobao.org'

gem 'rails', '4.2.3'
gem 'sass-rails', '5.0.6'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development do
  gem 'quiet_assets'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  gem 'rspec-rails', '~> 3.0'
end

# 更友好的出错页面
group :test, :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'database_cleaner', '~> 1.4.1'
  gem "factory_girl_rails"
  gem 'capybara'
end

gem 'mongoid', '~> 4.0.2'
gem 'haml'

gem 'play_auth', :github => 'mindpin/play_auth',
                 :tag => :latest

gem 'mongoid_react_scaffold', path: '../'

# for semantic
gem 'semantic-ui-sass', '~> 2.2.2.2'

# for react
gem 'react-rails', '1.8.1'
gem 'sprockets-coffee-react', '4.0.0'

# 通过 rails assets 服务加载前端包
source 'https://rails-assets.org'
gem 'rails-assets-semantic'

#http://medialize.github.io/URI.js/
gem 'rails-assets-URIjs'
# http://facebook.github.io/immutable-js/
gem 'rails-assets-immutable'
# https://github.com/Olical/EventEmitter/blob/master/docs/guide.md
gem 'rails-assets-eventEmitter'
# for react end
